# GitHub Self-Hosted Runner
enabled: true
replicas: 2

githubTokenSecretName: bulk-submission-and-fee-scheme-tests-github-token
githubTokenSecretKey: token
githubRepository: ministryofjustice/bulk-submission-and-fee-scheme-tests-
runnerLabels: self-hosted,linux,uat,k8s

image:
  repository: ""
  tag: "latest"
  pullPolicy: Always

resources:
  requests:
    memory: "4Gi"
    cpu: "3000m"
  limits:
    memory: "8Gi"
    cpu: "6000m"
