# scripts/Dockerfile.localstack
# Newer versions require an Auth token
FROM localstack/localstack:3.8.1

COPY scripts/init-localstack.sh /etc/localstack/init/ready.d/init-localstack.sh
RUN chmod +x /etc/localstack/init/ready.d/init-localstack.sh