name: Run API Tests

on:
  push:
    branches: [ main, workflows ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: uat
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to the EKS cluster
        uses: ./.github/actions/authenticate-to-eks-cluster
        with:
          kube_cluster: ${{ secrets.kube_cluster }}
          kube_namespace: ${{ secrets.kube_namespace }}
          kube_token: ${{ secrets.kube_token }}
          kube_cert: ${{ secrets.kube_cert }}
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: npm

      - name: Create .env file
        shell: bash
        run: |
          cat <<EOF > .env
          API_BASE_URL=${{ secrets.API_BASE_URL }}
          API_TOKEN=${{ secrets.API_TOKEN }}
          EOF

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run API Tests
        run: |
          POD_LABEL="app.kubernetes.io/name=laa-fee-scheme-api"
          POD_NAME=$(kubectl get pod -n "$KUBE_NAMESPACE" -l "$POD_LABEL" -o jsonpath='{.items[0].metadata.name}')
          echo "Port forwarding pod: $POD_NAME"
          kubectl port-forward -n "$KUBE_NAMESPACE" pod/"$POD_NAME" 8085:8085 > pf.log 2>&1 &
          PORT_FORWARD_PID=$!
          echo "Port-forward started with PID $PORT_FORWARD_PID"

          npm run test:api
