name: Run E2E Tests via Docker Compose

concurrency:
  group: run-e2e-tests
  cancel-in-progress: false

on:
  push:
    branches: [ feature/test-compose ]

  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run tests against'
        required: false
        default: 'main'

  schedule:
    # 6pm UTC Mon–Fri
    - cron: '0 18 * * 1-5'

jobs:
  ui-tests:
    runs-on: ubuntu-latest
    permissions:
     id-token: write
     contents: read
     packages: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch || github.ref }}

      - name: Log in to GHCR
        run: |
          echo "${{ github.token }}" | docker login ghcr.io \
            -u ${{ github.actor }} --password-stdin

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ECR_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.ECR_REGION }}

      - name: Login ecr
        uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr

      - name: Get latest SaBC version
        run: |
          LATEST_TAG=$(aws ecr list-images \
            --repository-name ${{ vars.ECR_REPOSITORY }} \
            --query 'imageIds[*].imageTag' \
            --region eu-west-2 \
            --output text | tr ' ' '\n' | sort -V | tail -n1)
          echo "LATEST_SABC=TAG=$LATEST_TAG" >> $GITHUB_ENV

      - name: Print LATEST_SABC
        run: |
          echo "LATEST_SABC value: ${{ env.LATEST_SABC }}"

      - name: Run services
        shell: bash
        run: |
          docker compose -f docker-compose.yml up -d
        env:
          ECR_ACCOUNT: ${{ secrets.ECR_ACCOUNT }}
          ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
          ECR_REGION: ${{ vars.ECR_REGION }}
          SABC_VERSION: ${{ env.LATEST_SABC }}

      - name: Wait for services
        shell: bash
        run: |
          docker compose -f docker-compose.yml ps

      - name: Tear down
        if: ${{ always() }}
        shell: bash
        run: |
          docker compose down -v;