name: Run E2E Tests via Docker Compose

concurrency:
  group: run-e2e-tests
  cancel-in-progress: false

on:
  push:
    branches: [ feature/test-compose ]

  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run tests against'
        required: false
        default: 'main'

  schedule:
    # 6pm UTC Mon–Fri
    - cron: '0 18 * * 1-5'

jobs:
  ui-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch || github.ref }}

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ECR_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.ECR_REGION }}

      - name: Login ecr
        uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr

      - name: Run services
        shell: bash
        run: |
          docker compose -f docker-compose.yml up -d

      - name: Wait for services
        shell: bash
        run: |
          docker compose -f docker-compose.yml ps

      - name: Tear down
        if: ${{ always() }}
        working-directory: ./laa-data-claims-parent
        shell: bash
        run: |
          docker compose down claims-api event-service sabc-ui -v;